# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Development container base image for crosvm on Asahi Fedora Remix (aarch64).
# Replaces the Debian-based base image. No foreign architectures or cross-
# compilation toolchains are included.

FROM docker.io/fedora:latest

# Use ./tools/deps/install-aarch64-rpms to install all RPM packages
COPY --chmod=555 \
    tools/deps/install-aarch64-rpms \
    /tools/deps/

RUN cd /tools/deps \
    && dnf install --assumeyes sudo curl \
    && ./install-aarch64-rpms \
    && dnf clean all \
    && rm -rf /var/cache/dnf
