#!/usr/bin/env bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Sets up a native aarch64 development environment on Asahi Fedora Remix.
# Replaces both tools/setup (x86_64) and tools/setup-aarch64.

set -ex

$(dirname $0)/deps/install-aarch64-rpms
$(dirname $0)/deps/install-aarch64-other
$(dirname $0)/deps/install_rutabaga_gfx_deps

Red='\033[0;31m'
Reset='\033[0m'

# Check if submodules were initialized.
if git submodule status | grep '^-'; then
    echo >&2 -e "${Red}ERROR${Reset}: Git modules were not initialized. Run 'git submodule update --init' to initialize them."
fi
